'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run',
    'lumi',
    'event',
    'nvtx',
    'tau_reco_mass',
    'tau_reco_pt',
    'tau_reco_eta',
    'tau_reco_phi',
    'tau_reco_charge',
    'tau_reco_decaymode',
    'tau_reco_ip3d'    ,
    'tau_reco_dxy'     ,
    'tau_reco_pixel'   ,
    'tau_l1_pt',
    'tau_l1_eta',
    'tau_l1_phi',
    'tau_l1_charge',
    'tau_l1_iso',
    'jet_l1_pt',
    'jet_l1_eta',
    'jet_l1_phi',
    'jet_l1_charge',
    'tau_com_pt'   ,  
    'tau_com_eta'   , 
    'tau_com_phi'    ,
    'tau_com_charge' ,
    'tau_upcom_pt'   ,  
    'tau_gen_pt',
    'tau_gen_eta',
    'tau_gen_phi',
    'tau_gen_charge',
    'tau_gen_decaymode',
    'tau_gen_vis_mass',
    'tau_gen_vis_pt',
    'tau_gen_vis_eta',
    'tau_gen_vis_phi',
    'tau_gen_lxy', 
    'tau_gen_vx',  
    'tau_gen_vy',  
    'tau_gen_vz',  
    'tau_gen_cosxy',  
    'tau_gen_momct',  
    'tau_gen_momct2d',  
    'tau_gen_mom_mass',  
    'jet_mass',
    'jet_pt',
    'jet_eta',
    'jet_phi',
    'jet_charge',
    'PV_x',
    'PV_y',
    'PV_z',

]