'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run',
    'lumi',
    'event',
    'trueNI',
    'nvtx',
    'tau_reco_mass',
    'tau_reco_pt',
    'tau_reco_eta',
    'tau_reco_phi',
    'tau_reco_charge',
    'tau_reco_decaymode',
    'tau_reco_npix',
    'tau_L2_mass',
    'tau_L2_pt',
    'tau_L2_eta',
    'tau_L2_phi',
    'tau_L2_charge',

    'tau_isoL2_mass',
    'tau_isoL2_pt',
    'tau_isoL2_eta',
    'tau_isoL2_phi',
    'tau_isoL2_charge',

    'tau_hltPFjet_mass'   ,
    'tau_hltPFjet_pt'     ,
    'tau_hltPFjet_eta'    ,
    'tau_hltPFjet_phi'    ,
    'tau_hltPFjet_charge' ,

    'tau_hltPFtau_mass'   ,
    'tau_hltPFtau_pt'     ,
    'tau_hltPFtau_eta'    ,
    'tau_hltPFtau_phi'    ,
    'tau_hltPFtau_charge' ,
    'tau_hltPFtau_decaymode' ,
    
    'tau_hltPFdispltau_mass'    ,
    'tau_hltPFdispltau_pt'      ,
    'tau_hltPFdispltau_eta'     ,
    'tau_hltPFdispltau_phi'     ,
    'tau_hltPFdispltau_charge'  ,
    'tau_hltPFdispltau_decaymode'  ,

    'tau_hltPFdispltau_leadChargedCandPdgId',
    'tau_hltPFdispltau_leadChargedCandPt'   ,
    'tau_hltPFdispltau_leadNeutralCandPdgId',
    'tau_hltPFdispltau_leadNeutralCandPt'   ,
    'tau_hltPFdispltau_leadPFCandPdgId'     ,
    'tau_hltPFdispltau_leadPFCandPt'        ,
    'tau_hltPFdispltau_maxHCALPFClusterEt',
    'tau_hltPFdispltau_nChargedHad',
    'tau_hltPFdispltau_nGamma'     ,
    'tau_hltPFdispltau_sumPtCharged',
    'tau_hltPFdispltau_sumPtNeutral',

    'tau_hltPFdispltau_dxy'  ,
    'tau_hltPFdispltau_dxyerr'  ,
    'tau_hltPFdispltau_ip3d'  ,
    'tau_hltPFdispltau_ip3derr'  ,

    'tau_hltPFdispltau_passChargedIso'  ,
    'tau_hltPFdispltau_passRelChargedIso'  ,
    'tau_hltPFdispltau_passAbsChargedIso'  ,
    'tau_hltPFdispltau_isoval',
    'tau_hltPFdispltau_passFilters',

    'tau_hltPFdispltau_0_pt'      ,
    'tau_hltPFdispltau_0_eta'     ,
    'tau_hltPFdispltau_0_phi'     ,
    'tau_hltPFdispltau_0_charge'  ,
    'tau_hltPFdispltau_0_decaymode'  ,
    'tau_hltPFdispltau_1_pt'      ,
    'tau_hltPFdispltau_1_eta'     ,
    'tau_hltPFdispltau_1_phi'     ,
    'tau_hltPFdispltau_1_charge'  ,
    'tau_hltPFdispltau_1_decaymode'  ,
    'tau_hltPFdispltau_2_pt'      ,
    'tau_hltPFdispltau_2_eta'     ,
    'tau_hltPFdispltau_2_phi'     ,
    'tau_hltPFdispltau_2_charge'  ,
    'tau_hltPFdispltau_2_decaymode'  ,

    'tau_hlttaumatchmom_pt'       ,
    'tau_hlttaumatchmom_eta'      ,
    'tau_hlttaumatchmom_phi'      ,
    'tau_hlttaumatchmom_charge'   ,
    'tau_hlttaumatchmom_decaymode',
    
    'tau_hltPF_pt'     ,
    'tau_hltPF_eta'    ,
    'tau_hltPF_phi'    ,
    'tau_hltPF_charge' ,
    'tau_hltPF_pdgid'  ,
    'tau_hltPFpi_pt'     ,
    'tau_hltPFpi_eta'    ,
    'tau_hltPFpi_phi'    ,
    'tau_hltPFpi_charge' ,

    'tau_hltTk_pt'     ,
    'tau_hltTk_eta'    ,
    'tau_hltTk_phi'    ,
    'tau_hltTk_charge' ,

    'tau_hltIt4Tk_pt'     ,
    'tau_hltIt4Tk_eta'    ,
    'tau_hltIt4Tk_phi'    ,
    'tau_hltIt4Tk_charge' ,
    'tau_hltIt04Tk_pt'     ,
    'tau_hltIt04Tk_eta'    ,
    'tau_hltIt04Tk_phi'    ,
    'tau_hltIt04Tk_charge' ,
    
    'tau_hltMuMTk_pt'     ,
    'tau_hltMuMTk_eta'    ,
    'tau_hltMuMTk_phi'    ,
    'tau_hltMuMTk_charge' ,

    'tau_offtk_pt'     ,
    'tau_offtk_eta'    ,
    'tau_offtk_phi'    ,
    'tau_offtk_charge' ,
    'tau_offtk_algo',
    'tau_reco_tau_mass'     ,
    'tau_reco_tau_pt'       ,
    'tau_reco_tau_eta'      ,
    'tau_reco_tau_phi'      ,
    'tau_reco_tau_charge'   ,
    'tau_reco_tau_decaymode',

#     'tau_hltTk_dxy' ,
    'tau_l1_pt',
    'tau_l1_eta',
    'tau_l1_phi',
    'tau_l1_charge',
    'tau_l1_iso',

    'mu_l3_pt'    ,
    'mu_l3_eta'   ,
    'mu_l3_phi'   ,
    'mu_l3_charge',

    'tau_l1_emu_pt',
    'tau_l1_emu_eta',
    'tau_l1_emu_phi',
    'tau_l1_emu_charge',
    'tau_l1_emu_iso',

    'jet_l1_pt',
    'jet_l1_eta',
    'jet_l1_phi',
    'jet_l1_charge',
    'tau_gen_ndau',
    'tau_gen_pt',
    'tau_gen_eta',
    'tau_gen_phi',
    'tau_gen_charge',
    'tau_gen_decaymode',
    'tau_gen_vis_mass',
    'tau_gen_vis_pt',
    'tau_gen_vis_eta',
    'tau_gen_vis_phi',
    'tau_gen_dau_pt' ,
    'tau_gen_dau_eta',
    'tau_gen_dau_phi',
    'tau_gen_lxy', 
    'tau_gen_dxy',  
    'tau_gen_visdxy',  
    'tau_gen_vx',  
    'tau_gen_vy',  
    'tau_gen_vz',  
    'tau_gen_cosxy',  
    'tau_gen_momct',  
    'tau_gen_momct2d',  
    'tau_gen_mom_mass', 
    'tau_gen_mom_pt', 
    'tau_gen_mom_eta', 
    'tau_gen_mom_phi', 
    'tau_gen_pi_lxy'     ,
    'tau_gen_pi_cosxy'   ,
    'jet_mass',
    'jet_pt',
    'jet_eta',
    'jet_phi',
    'jet_charge',
    'PV_x',
    'PV_y',
    'PV_z',
]
