'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run',
    'lumi',
    'event',
    'trueNI',
    'nvtx',
    'tau_reco_mass',
    'tau_reco_pt',
    'tau_reco_eta',
    'tau_reco_phi',
    'tau_reco_charge',
    'tau_reco_decaymode',
    'tau_reco_npix',

    'tau_hltPFdispltau_mass'    ,
    'tau_hltPFdispltau_pt'      ,
    'tau_hltPFdispltau_eta'     ,
    'tau_hltPFdispltau_phi'     ,
    'tau_hltPFdispltau_charge'  ,
    'tau_hltPFdispltau_decaymode'  ,

    'tau_hltPFdispltau_leadChargedCandPdgId',
    'tau_hltPFdispltau_leadChargedCandPt'   ,
    'tau_hltPFdispltau_leadNeutralCandPdgId',
    'tau_hltPFdispltau_leadNeutralCandPt'   ,
    'tau_hltPFdispltau_leadPFCandPdgId'     ,
    'tau_hltPFdispltau_leadPFCandPt'        ,
    'tau_hltPFdispltau_maxHCALPFClusterEt',
    'tau_hltPFdispltau_nChargedHad',
    'tau_hltPFdispltau_nGamma'     ,
    'tau_hltPFdispltau_sumPtCharged',
    'tau_hltPFdispltau_sumPtNeutral',

    'tau_hltPFdispltau_dxy'  ,
    'tau_hltPFdispltau_dxyerr'  ,
    'tau_hltPFdispltau_ip3d'  ,
    'tau_hltPFdispltau_ip3derr'  ,

    'tau_hltPFdispltau_passChargedIso'  ,
    'tau_hltPFdispltau_passRelChargedIso'  ,
    'tau_hltPFdispltau_passAbsChargedIso'  ,
    'tau_hltPFdispltau_isoval',
    'tau_hltPFdispltau_passFilters',

    'tau_hlttaumatchmom_pt'       ,
    'tau_hlttaumatchmom_eta'      ,
    'tau_hlttaumatchmom_phi'      ,
    'tau_hlttaumatchmom_charge'   ,
    'tau_hlttaumatchmom_decaymode',

    'tau_offtk_pt'     ,
    'tau_offtk_eta'    ,
    'tau_offtk_phi'    ,
    'tau_offtk_charge' ,
    'tau_offtk_algo',
    'tau_reco_tau_mass'     ,
    'tau_reco_tau_pt'       ,
    'tau_reco_tau_eta'      ,
    'tau_reco_tau_phi'      ,
    'tau_reco_tau_charge'   ,
    'tau_reco_tau_decaymode',

#     'tau_hltTk_dxy' ,
    'tau_l1_pt',
    'tau_l1_eta',
    'tau_l1_phi',
    'tau_l1_charge',
    'tau_l1_iso',

    'tau_l1mu_pt'    ,
    'tau_l1mu_eta'   ,
    'tau_l1mu_phi'   ,
    'tau_l1mu_charge',
    'tau_l1mu18_pt'    ,
    'tau_l1mu18_eta'   ,
    'tau_l1mu18_phi'   ,
    'tau_l1mu18_charge',
    'tau_l3mu_pt'    ,
    'tau_l3mu_eta'   ,
    'tau_l3mu_phi'   ,
    'tau_l3mu_charge',
    'tau_isomu_pt'    ,
    'tau_isomu_eta'   ,
    'tau_isomu_phi'   ,
    'tau_isomu_charge',

    'tau_l2disp_pt'    ,
    'tau_l2disp_eta'   ,
    'tau_l2disp_phi'   ,
    'tau_l2disp_charge',
    'tau_cascade_pt'    ,
    'tau_cascade_eta'   ,
    'tau_cascade_phi'   ,
    'tau_cascade_charge',
    'tau_cascade_dxy',
    'tau_glb_pt'    ,
    'tau_glb_eta'   ,
    'tau_glb_phi'   ,
    'tau_glb_charge',
    'tau_glb_dxy'   ,

    'mu_gen_ndau',
    'mu_gen_pt',
    'mu_gen_eta',
    'mu_gen_phi',
    'mu_gen_charge',
    'mu_gen_lxy', 
    'mu_gen_dxy',  
    'mu_gen_vx',  
    'mu_gen_vy',  
    'mu_gen_vz',  
    'mu_gen_cosxy',  
    'mu_gen_mom_mass', 
    'mu_gen_mom_pt', 
    'mu_gen_mom_eta', 
    'mu_gen_mom_phi', 
    'mu_gen_momct2d',  
    'mu_gen_vis_mass',
    'mu_gen_vis_pt',
    'mu_gen_vis_eta',
    'mu_gen_vis_phi',

    'tau_gen_vis_mass',
    'tau_gen_vis_pt',
    'tau_gen_vis_eta',
    'tau_gen_vis_phi',
    'tau_gen_dau_pt' ,
    'tau_gen_dau_eta',
    'tau_gen_dau_phi',
    'tau_gen_lxy', 
    'tau_gen_dxy',  
    'tau_gen_visdxy',  
    'tau_gen_vx',  
    'tau_gen_vy',  
    'tau_gen_vz',  
    'tau_gen_cosxy',  
    'tau_gen_momct',  
    'tau_gen_momct2d',  
    'tau_gen_mom_mass', 
    'tau_gen_mom_pt', 
    'tau_gen_mom_eta', 
    'tau_gen_mom_phi', 

    'tau_gen_ndau',
    'tau_gen_pt',
    'tau_gen_eta',
    'tau_gen_phi',
    'tau_gen_charge',
    'tau_gen_decaymode',

    'PV_x',
    'PV_y',
    'PV_z',
]
