'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run',
    'lumi',
    'event',
    'pass_old_hlt',
    'pass_PFMET120_PFMHT120_IDTight', 
    'pass_PFMET130_PFMHT130_IDTight', 
    'pass_PFMET140_PFMHT140_IDTight', 
    'pass_PFMETNoMu110_PFMHTNoMu110_IDTight', 
    'pass_PFMETNoMu120_PFMHTNoMu120_IDTight', 
    'pass_PFMETNoMu130_PFMHTNoMu130_IDTight', 
    'pass_PFMETNoMu140_PFMHTNoMu140_IDTight', 
    'pass_DoubleMediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg', 
    'pass_MediumChargedIsoPFTau50_Trk30_eta2p1_1pr_MET100', 
    'pass_MediumChargedIsoPFTau50_Trk30_eta2p1_1pr_MET110', 
    'pass_MediumChargedIsoPFTau50_Trk30_eta2p1_1pr_MET120', 
    'pass_MediumChargedIsoPFTau50_Trk30_eta2p1_1pr_MET130', 
    'pass_MediumChargedIsoPFTau50_Trk30_eta2p1_1pr_MET140', 
    'pass_MET105_IsoTrk50', 
    'pass_MET120_IsoTrk50',
    'trueNI',
    'nvtx',
    'tau_reco_mass',
    'tau_reco_pt',
    'tau_reco_eta',
    'tau_reco_phi',
    'tau_reco_charge',
    'tau_reco_decaymode',
    'tau_reco_npix',
    'tau_L2_mass',
    'tau_L2_pt',
    'tau_L2_eta',
    'tau_L2_phi',
    'tau_L2_charge',

    'tau_isoL2_mass',
    'tau_isoL2_pt',
    'tau_isoL2_eta',
    'tau_isoL2_phi',
    'tau_isoL2_charge',
    'tau_isoL2fo_mass',
    'tau_isoL2fo_pt',
    'tau_isoL2fo_eta',
    'tau_isoL2fo_phi',
    'tau_isoL2fo_charge',
    
    'tau_hltPFdispltau_mass'    ,
    'tau_hltPFdispltau_pt'      ,
    'tau_hltPFdispltau_eta'     ,
    'tau_hltPFdispltau_phi'     ,
    'tau_hltPFdispltau_charge'  ,
    'tau_hltPFdispltau_decaymode'  ,

    'tau_hltPFdispltau_leadChargedCandPdgId',
    'tau_hltPFdispltau_leadChargedCandPt'   ,
    'tau_hltPFdispltau_leadNeutralCandPdgId',
    'tau_hltPFdispltau_leadNeutralCandPt'   ,
    'tau_hltPFdispltau_leadPFCandPdgId'     ,
    'tau_hltPFdispltau_leadPFCandPt'        ,
    'tau_hltPFdispltau_maxHCALPFClusterEt',
    'tau_hltPFdispltau_nChargedHad',
    'tau_hltPFdispltau_nGamma'     ,
    'tau_hltPFdispltau_sumPtCharged',
    'tau_hltPFdispltau_sumPtNeutral',

    'tau_hltPFdispltau_dxy'  ,
    'tau_hltPFdispltau_dxyerr'  ,
    'tau_hltPFdispltau_ip3d'  ,
    'tau_hltPFdispltau_ip3derr'  ,

    'tau_hltPFdispltau_passChargedIso'  ,
    'tau_hltPFdispltau_passRelChargedIso'  ,
    'tau_hltPFdispltau_passAbsChargedIso'  ,
    'tau_hltPFdispltau_isoval',
    'tau_hltPFdispltau_passFilters',

    'tau_l1_pt',
    'tau_l1_eta',
    'tau_l1_phi',
    'tau_l1_charge',
    'tau_l1_iso',

    'tau_gen_ndau',
    'tau_gen_pt',
    'tau_gen_eta',
    'tau_gen_phi',
    'tau_gen_charge',
    'tau_gen_decaymode',
    'tau_gen_vis_mass',
    'tau_gen_vis_pt',
    'tau_gen_vis_eta',
    'tau_gen_vis_phi',
    'tau_gen_dau_pt' ,
    'tau_gen_dau_eta',
    'tau_gen_dau_phi',
    'tau_gen_lxy', 
    'tau_gen_dxy',  
    'tau_gen_visdxy',  
    'tau_gen_vx',  
    'tau_gen_vy',  
    'tau_gen_vz',  
    'tau_gen_cosxy',  
    'tau_gen_momct',  
    'tau_gen_momct2d',  
    'tau_gen_mom_mass', 
    'tau_gen_mom_pt', 
    'tau_gen_mom_eta', 
    'tau_gen_mom_phi', 
    'tau_gen_pi_lxy'     ,
    'tau_gen_pi_cosxy'   ,
    'jet_mass',
    'jet_pt',
    'jet_eta',
    'jet_phi',
    'jet_charge',
    'PV_x',
    'PV_y',
    'PV_z',
]
