'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run',
    'lumi',
    'event',
    'trueNI',
    'nvtx',
    'gen_met',

    'pass_met_hlt',
    'pass_lep_hlt',
    'pass_EGTau_hlt',
    'pass_EGTau_obj',
    'pass_EGOnly_obj',
    'pass_PFMET120_PFMHT120_IDTight', 
    'pass_PFMET130_PFMHT130_IDTight', 
    'pass_PFMET140_PFMHT140_IDTight', 
    'pass_PFMETNoMu110_PFMHTNoMu110_IDTight', 
    'pass_PFMETNoMu120_PFMHTNoMu120_IDTight', 
    'pass_PFMETNoMu130_PFMHTNoMu130_IDTight', 
    'pass_PFMETNoMu140_PFMHTNoMu140_IDTight', 
    'pass_DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1',    
    'pass_MET105_IsoTrk50', 
    'pass_MET120_IsoTrk50',
    'pass_Ele30_WPTight_Gsf',
    'pass_Photon200',
    'pass_Photon20',
    'pass_Photon30_R9Id90_CaloIdL_IsoL_DisplacedIdL',

    'gen_tau_ele_dr'  ,
    'hlt_tau_mass'    ,
    'hlt_tau_pt'      ,
    'hlt_tau_eta'     ,
    'hlt_tau_phi'     ,
    'hlt_tau_charge'  ,
    'hlt_tau_decaymode'  ,
    'hlt_tau_dxy'  ,
    'hlt_tau_dxyerr'  ,
    'hlt_tau_ip3d'  ,
    'hlt_tau_ip3derr'  ,
    'hlt_tau_passFilters',

    'l1_tau_pt',
    'l1_tau_eta',
    'l1_tau_phi',
    'l1_tau_charge',
    'l1_tau_iso',

     ## egamma variables
    'l1_ele_pt'    ,
    'l1_ele_eta'   ,
    'l1_ele_phi'   ,
    'l1_ele_charge',
    'l1_ele_hwiso',
    'l1_ele_passselel1',
    'l1_ele_passeletaul1',
    'l1_ele_passgsfelel1',


    'l1_ele_filter_pt'    ,
    'l1_ele_filter_eta'   ,
    'l1_ele_filter_phi'   ,
    'l1_ele_filter_charge',
    'hlt_ele_pt'    ,
    'hlt_ele_eta'   ,
    'hlt_ele_phi'   ,
    'hlt_ele_charge',
    'hlt_ele_r9',
    'hlt_ele_clsh',
    'hlt_ele_eiso',
    'hlt_ele_hiso',
    'hlt_ele_tiso',
    'hlt_ele_smin',
    'hlt_ele_smaj',
    'hlt_ele_passFilters',
    'hlt_ele_passSingleEGFilters',
    'hlt_ele_passSingleL1Filter',
    'hlt_ele_matched_mom',

    'hlt_gsfele_pt'    ,
    'hlt_gsfele_eta'   ,
    'hlt_gsfele_phi'   ,
    'hlt_gsfele_passFilters',
    'hlt_gsfele_matched_mom',

    'filter1_ele_pt'    ,
    'filter1_ele_eta'   ,
    'filter1_ele_phi'   ,
#     'filter1_ele_charge',

    'filter2_ele_pt'    ,
    'filter2_ele_eta'   ,
    'filter2_ele_phi'   ,
#     'filter2_ele_charge',

    'filter3_ele_pt'    ,
    'filter3_ele_eta'   ,
    'filter3_ele_phi'   ,
#     'filter3_ele_charge',

    'filter4_ele_pt'    ,
    'filter4_ele_eta'   ,
    'filter4_ele_phi'   ,
#     'filter4_ele_charge',

    'filter5_ele_pt'    ,
    'filter5_ele_eta'   ,
    'filter5_ele_phi'   ,
#     'filter5_ele_charge',

    'filter6_ele_pt'    ,
    'filter6_ele_eta'   ,
    'filter6_ele_phi'   ,
#     'filter6_ele_charge',

    'filter7_ele_pt'    ,
    'filter7_ele_eta'   ,
    'filter7_ele_phi'   ,
#     'filter7_ele_charge',

    'filter8_ele_pt'    ,
    'filter8_ele_eta'   ,
    'filter8_ele_phi'   ,
#     'filter8_ele_charge',

    'filter9_ele_pt'    ,
    'filter9_ele_eta'   ,
    'filter9_ele_phi'   ,


    'filter1_tightele_pt'    ,
    'filter1_tightele_eta'   ,
    'filter1_tightele_phi'   ,
#     'filter1_tightele_charge',

    'filter2_tightele_pt'    ,
    'filter2_tightele_eta'   ,
    'filter2_tightele_phi'   ,
#     'filter2_tightele_charge',

    'filter3_tightele_pt'    ,
    'filter3_tightele_eta'   ,
    'filter3_tightele_phi'   ,
#     'filter3_tightele_charge',

    'filter4_tightele_pt'    ,
    'filter4_tightele_eta'   ,
    'filter4_tightele_phi'   ,
#     'filter4_tightele_charge',

    'filter5_tightele_pt'    ,
    'filter5_tightele_eta'   ,
    'filter5_tightele_phi'   ,
#     'filter5_tightele_charge',

    'filter6_tightele_pt'    ,
    'filter6_tightele_eta'   ,
    'filter6_tightele_phi'   ,
#     'filter6_tightele_charge',

    'filter7_tightele_pt'    ,
    'filter7_tightele_eta'   ,
    'filter7_tightele_phi'   ,
#     'filter7_tightele_charge',

    'filter8_tightele_pt'    ,
    'filter8_tightele_eta'   ,
    'filter8_tightele_phi'   ,
#     'filter8_tightele_charge',

    'filter9_tightele_pt'    ,
    'filter9_tightele_eta'   ,
    'filter9_tightele_phi'   ,

    'gen_ele_ndau',
    'gen_ele_pt',
    'gen_ele_eta',
    'gen_ele_phi',
    'gen_ele_charge',
    'gen_ele_lxy', 
    'gen_ele_lxy_ele', 
    'gen_ele_dxy',  
    'gen_ele_vx',  
    'gen_ele_vy',  
    'gen_ele_vz',  
#     'gen_ele_cosxy',  
    'gen_ele_mom_mass', 
    'gen_ele_mom_pt', 
    'gen_ele_mom_eta', 
    'gen_ele_mom_phi', 
    'gen_ele_momct2d',  
    'gen_ele_vis_mass',
    'gen_ele_vis_pt',
    'gen_ele_vis_eta',
    'gen_ele_vis_phi',

    'gen_tau_vis_mass',
    'gen_tau_vis_pt',
    'gen_tau_vis_eta',
    'gen_tau_vis_phi',
    'gen_tau_dau_pt' ,
    'gen_tau_dau_eta',
    'gen_tau_dau_phi',
    'gen_tau_lxy', 
    'gen_tau_dxy',  
    'gen_tau_visdxy',  
    'gen_tau_vx',  
    'gen_tau_vy',  
    'gen_tau_vz',  
#     'gen_tau_cosxy',  
    'gen_tau_momct',  
    'gen_tau_momct2d',  
    'gen_tau_mom_mass', 
    'gen_tau_mom_pt', 
    'gen_tau_mom_eta', 
    'gen_tau_mom_phi', 

    'gen_tau_ndau',
    'gen_tau_pt',
    'gen_tau_eta',
    'gen_tau_phi',
    'gen_tau_charge',
    'gen_tau_decaymode',
]
